In [1]:
# 6.S083 Pset 1 - Saumya Rawat

In [2]:
# Exercise 1: Visualizing the data over time

In [3]:
url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"

"https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"

In [4]:
download(url, "covid_data.csv")

"covid_data.csv"

In [5]:
using Pkg   # built-in package manager in Julia: Pkg
Pkg.add("CSV")   # calls the `add` function from the module Pkg.  This installs a package
Pkg.add("Interact")

   Updating registry at `~/.julia/registries/General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
 [no changes]
   Updating `~/.julia/environments/v1.4/Manifest.toml`
 [no changes]
  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
 [no changes]
   Updating `~/.julia/environments/v1.4/Manifest.toml`
 [no changes]


In [6]:
using CSV   # Comma Separated Values

In [7]:
data = CSV.read("covid_data.csv")  # run the function `read` from the package CSV

263×81 DataFrames.DataFrame. Omitted printing of 78 columns
│ Row │ Province/State                   │ Country/Region        │ Lat      │
│     │ Union{Missing, String}           │ String                │ Float64  │
├─────┼──────────────────────────────────┼───────────────────────┼──────────┤
│ 1   │ missing                          │ Afghanistan           │ 33.0     │
│ 2   │ missing                          │ Albania               │ 41.1533  │
│ 3   │ missing                          │ Algeria               │ 28.0339  │
│ 4   │ missing                          │ Andorra               │ 42.5063  │
│ 5   │ missing                          │ Angola                │ -11.2027 │
│ 6   │ missing                          │ Antigua and Barbuda   │ 17.0608  │
│ 7   │ missing                          │ Argentina             │ -38.4161 │
│ 8   │ missing                          │ Armenia               │ 40.0691  │
│ 9   │ Australian Capital Territory     │ Australia             │ -35.4735 │
│ 10  │ New South Wales                  │ Australia             │ -33.8688 │
⋮
│ 253 │ missing                          │ MS Zaandam            │ 0.0      │
│ 254 │ missing                          │ Botswana              │ -22.3285 │
│ 255 │ missing                          │ Burundi               │ -3.3731  │
│ 256 │ missing                          │ Sierra Leone          │ 8.46056  │
│ 257 │ Bonaire, Sint Eustatius and Saba │ Netherlands           │ 12.1784  │
│ 258 │ missing                          │ Malawi                │ -13.2543 │
│ 259 │ Falkland Islands (Malvinas)      │ United Kingdom        │ -51.7963 │
│ 260 │ Saint Pierre and Miquelon        │ France                │ 46.8852  │
│ 261 │ missing                          │ South Sudan           │ 6.877    │
│ 262 │ missing                          │ Western Sahara        │ 24.2155  │
│ 263 │ missing                          │ Sao Tome and Principe │ 0.18636  │

In [8]:
all_countries = collect(data[:, 2])

263-element Array{String,1}:
 "Afghanistan"
 "Albania"
 "Algeria"
 "Andorra"
 "Angola"
 "Antigua and Barbuda"
 "Argentina"
 "Armenia"
 "Australia"
 "Australia"
 "Australia"
 "Australia"
 "Australia"
 ⋮
 "United Kingdom"
 "MS Zaandam"
 "Botswana"
 "Burundi"
 "Sierra Leone"
 "Netherlands"
 "Malawi"
 "United Kingdom"
 "France"
 "South Sudan"
 "Western Sahara"
 "Sao Tome and Principe"

In [9]:
countries = ["China", "Japan", "South Korea", "US", "United Kingdom", "France", "Germany"]

7-element Array{String,1}:
 "China"
 "Japan"
 "South Korea"
 "US"
 "United Kingdom"
 "France"
 "Germany"

In [10]:
col_names = names(data)

81-element Array{Symbol,1}:
 Symbol("Province/State")
 Symbol("Country/Region")
 :Lat
 :Long
 Symbol("1/22/20")
 Symbol("1/23/20")
 Symbol("1/24/20")
 Symbol("1/25/20")
 Symbol("1/26/20")
 Symbol("1/27/20")
 Symbol("1/28/20")
 Symbol("1/29/20")
 Symbol("1/30/20")
 ⋮
 Symbol("3/27/20")
 Symbol("3/28/20")
 Symbol("3/29/20")
 Symbol("3/30/20")
 Symbol("3/31/20")
 Symbol("4/1/20")
 Symbol("4/2/20")
 Symbol("4/3/20")
 Symbol("4/4/20")
 Symbol("4/5/20")
 Symbol("4/6/20")
 Symbol("4/7/20")

In [11]:
dates_sym = col_names[5:end]

77-element Array{Symbol,1}:
 Symbol("1/22/20")
 Symbol("1/23/20")
 Symbol("1/24/20")
 Symbol("1/25/20")
 Symbol("1/26/20")
 Symbol("1/27/20")
 Symbol("1/28/20")
 Symbol("1/29/20")
 Symbol("1/30/20")
 Symbol("1/31/20")
 Symbol("2/1/20")
 Symbol("2/2/20")
 Symbol("2/3/20")
 ⋮
 Symbol("3/27/20")
 Symbol("3/28/20")
 Symbol("3/29/20")
 Symbol("3/30/20")
 Symbol("3/31/20")
 Symbol("4/1/20")
 Symbol("4/2/20")
 Symbol("4/3/20")
 Symbol("4/4/20")
 Symbol("4/5/20")
 Symbol("4/6/20")
 Symbol("4/7/20")

In [12]:
date_strings = String.(names(data))[5:end]  # apply String function to each element

77-element Array{String,1}:
 "1/22/20"
 "1/23/20"
 "1/24/20"
 "1/25/20"
 "1/26/20"
 "1/27/20"
 "1/28/20"
 "1/29/20"
 "1/30/20"
 "1/31/20"
 "2/1/20"
 "2/2/20"
 "2/3/20"
 ⋮
 "3/27/20"
 "3/28/20"
 "3/29/20"
 "3/30/20"
 "3/31/20"
 "4/1/20"
 "4/2/20"
 "4/3/20"
 "4/4/20"
 "4/5/20"
 "4/6/20"
 "4/7/20"

In [13]:
using Dates
format = Dates.DateFormat("m/d/Y")
dates = parse.(Date, date_strings,format) .+ Year(2000)

77-element Array{Date,1}:
 2020-01-22
 2020-01-23
 2020-01-24
 2020-01-25
 2020-01-26
 2020-01-27
 2020-01-28
 2020-01-29
 2020-01-30
 2020-01-31
 2020-02-01
 2020-02-02
 2020-02-03
 ⋮
 2020-03-27
 2020-03-28
 2020-03-29
 2020-03-30
 2020-03-31
 2020-04-01
 2020-04-02
 2020-04-03
 2020-04-04
 2020-04-05
 2020-04-06
 2020-04-07

In [14]:
num_days = length(dates)

77

In [15]:
data_dict = Dict{String,Array}()

Dict{String,Array} with 0 entries

In [16]:
for current_country in countries
    matching_rows = data[[startswith(country,current_country) for country in all_countries],:]
    data_dict[current_country] = get(data_dict,current_country,zeros(num_days))
    prev_dict_values = get(data_dict,current_country,zeros(num_days))
    
    for row in eachrow(matching_rows)
        values = convert(Vector, row[5:end])
        
        data_dict[current_country] =data_dict[current_country] .+ values
        if current_country == "United Kingdom"
#             print(values)
#             print(data_dict[current_country] )
        end
        
    end
end

data_dict

Dict{String,Array} with 7 entries:
  "Germany"        => [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 4.0, 4.0, 4.0, 5.0  …  620…
  "South Korea"    => [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0…
  "United Kingdom" => [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0  …  197…
  "China"          => [548.0, 643.0, 920.0, 1406.0, 2075.0, 2877.0, 5509.0, 608…
  "Japan"          => [2.0, 2.0, 2.0, 2.0, 4.0, 4.0, 7.0, 7.0, 11.0, 15.0  …  1…
  "France"         => [0.0, 0.0, 2.0, 3.0, 3.0, 3.0, 4.0, 5.0, 5.0, 5.0  …  407…
  "US"             => [1.0, 1.0, 2.0, 2.0, 5.0, 5.0, 5.0, 5.0, 5.0, 7.0  …  140…

In [17]:
# Pkg.build("IJulia")
# Pkg.build("Plots")
# Pkg.build("Interact")
using Interact
using Plots

HTML{String}("<script>\n// Immediately-invoked-function-expression to avoid global variables.\n(function() {\n    var warning_div = document.getElementById(\"webio-warning-4713099569833833266\");\n    var hide = function () {\n        var script = document.getElementById(\"webio-setup-4206647725620466153\");\n        var parent = script && script.parentElement;\n        var grandparent = parent && parent.parentElement;\n        if (grandparent) {\n            grandparent.style.display = \"none\";\n        }\n        warning_div.style.display = \"none\";\n    };\n    if (typeof Jupyter !== \"undefined\") {\n        console.log(\"WebIO detected Jupyter notebook environment.\");\n        // Jupyter notebook.\n        var extensions = (\n            Jupyter\n            && Jupyter.notebook.config.data\n            && Jupyter.notebook.config.data.load_extensions\n        );\n        if (extensions && extensions[\"webio-jupyter-notebook\"]) {\n            // Extension already loaded.\n            console.log(\"Jupyter WebIO nbextension detected; not loading ad-hoc.\");\n            hide();\n            return;\n        }\n    } else if (window.location.pathname.includes(\"/lab\")) {\n        // Guessing JupyterLa\n        console.log(\"Jupyter Lab detected; make sure the @webio/jupyter-lab-provider labextension is installed.\");\n        hide();\n        return;\n    }\n})();\n\n</script>\n<p\n    id=\"webio-warning-4713099569833833266\"\n    class=\"output_text output_stderr\"\n    style=\"padding: 1em; font-weight: bold;\"\n>\n    Unable to load WebIO. Please make sure WebIO works for your Jupyter client.\n    For troubleshooting, please see <a href=\"https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/\">\n    the WebIO/IJulia documentation</a>.\n    <!-- TODO: link to installation docs. -->\n</p>\n")

In [18]:
@manipulate for day in 1:num_days
    plot()
    for current_country in countries
        amt = data_dict[current_country][1:day]
#         print(amt)
        amt = replace(amt, 0=>NaN)
        plot!(dates[1:day], amt, yscale=:log10, leg=:topleft, label=current_country, m=:o)
    end
    xlabel!("Date")
    ylabel!("Number of Confirmed Cases")
    title!("COVID-19 Cases")
end

#Ques 1.6: Yes, there is exponential growth.

Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Scope(Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :label), Any["day"], Dict{Symbol,Any}(:className => "interact ",:style => Dict{Any,Any}(:padding => "5px 10px 0px 10px")))], Dict{Symbol,Any}(:className => "interact-flex-row-left")), Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :input), Any[], Dict{Symbol,Any}(:max => 77,:min => 1,:attributes => Dict{Any,Any}(:type => "range",Symbol("data-bind") => "numericValue: index, valueUpdate: 'input', event: {change: function (){this.changes(this.changes()+1)}}","orient" => "horizontal"),:step => 1,:className => "slider slider is-fullwidth",:style => Dict{Any,Any}()))], Dict{Symbol,Any}(:className => "interact-flex-row-center")), Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :p), Any[], Dict{Symbol,Any}(:attributes => Dict("data-bind" => "text: formatted_val")))], Dict{Symbol,Any}(:className => "interact-flex-row-right"))], Dict{Symbol,Any}(:className => "interact-flex-row interact-widget")), Dict{String,Tuple{Observables.AbstractObservable,Union{Nothing, Bool}}}("changes" => (Observable{Int64} with 1 listeners. Value:
0, nothing),"index" => (Observable{Int64} with 2 listeners. Value:
39, nothing)), Set(String[]), nothing, Asset[Asset("js", "knockout", "/Users/saumyarawat/.julia/packages/Knockout/IP1uR/src/../assets/knockout.js"), Asset("js", "knockout_punches", "/Users/saumyarawat/.julia/packages/Knockout/IP1uR/src/../assets/knockout_punches.js"), Asset("js", nothing, "/Users/saumyarawat/.julia/packages/InteractBase/9mFwe/src/../assets/all.js"), Asset("css", nothing, "/Users/saumyarawat/.julia/packages/InteractBase/9mFwe/src/../assets/style.css"), Asset("css", nothing, "/Users/saumyarawat/.julia/packages/Interact/SbgIk/src/../assets/bulma_confined.min.css")], Dict{Any,Any}("changes" => Any[WebIO.JSString("(function (val){return (val!=this.model[\"changes\"]()) ? (this.valueFromJulia[\"changes\"]=true, this.model[\"changes\"](val)) : undefined})")],"index" => Any[WebIO.JSString("(function (val){return (val!=this.model[\"index\"]()) ? (this.valueFromJulia[\"index\"]=true, this.model[\"index\"](val)) : undefined})")]), WebIO.ConnectionPool(Channel{Any}(sz_max:32,sz_curr:0), Set(AbstractConnection[]), Base.GenericCondition{Base.AlwaysLockedST}(Base.InvasiveLinkedList{Task}(Task (runnable) @0x0000000121c718d0, Task (runnable) @0x0000000121c718d0), Base.AlwaysLockedST(1))), WebIO.JSString[WebIO.JSString("function () {\n    var handler = (function (ko, koPunches) {\n    ko.punches.enableAll();\n    ko.bindingHandlers.numericValue = {\n        init: function(element, valueAccessor, allBindings, data, context) {\n            var stringified = ko.observable(ko.unwrap(valueAccessor()));\n            stringified.subscribe(function(value) {\n                var val = parseFloat(value);\n                if (!isNaN(val)) {\n                    valueAccessor()(val);\n                }\n            });\n            valueAccessor().subscribe(function(value) {\n                var str = JSON.stringify(value);\n                if ((str == \"0\") && ([\"-0\", \"-0.\"].indexOf(stringified()) >= 0))\n                     return;\n                 if ([\"null\", \"\"].indexOf(str) >= 0)\n                     return;\n                stringified(str);\n            });\n            ko.applyBindingsToNode(\n                element,\n                {\n                    value: stringified,\n                    valueUpdate: allBindings.get('valueUpdate'),\n                },\n                context,\n            );\n        }\n    };\n    var json_data = {\"formatted_vals\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\

Exercise 2: Visualizing changes

In [19]:
total_cases_to_date = data_dict

Dict{String,Array} with 7 entries:
  "Germany"        => [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 4.0, 4.0, 4.0, 5.0  …  620…
  "South Korea"    => [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0…
  "United Kingdom" => [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0  …  197…
  "China"          => [548.0, 643.0, 920.0, 1406.0, 2075.0, 2877.0, 5509.0, 608…
  "Japan"          => [2.0, 2.0, 2.0, 2.0, 4.0, 4.0, 7.0, 7.0, 11.0, 15.0  …  1…
  "France"         => [0.0, 0.0, 2.0, 3.0, 3.0, 3.0, 4.0, 5.0, 5.0, 5.0  …  407…
  "US"             => [1.0, 1.0, 2.0, 2.0, 5.0, 5.0, 5.0, 5.0, 5.0, 7.0  …  140…

In [20]:
new_cases = Dict{String,Array}()

Dict{String,Array} with 0 entries

In [21]:
for current_country in countries
    new_cases[current_country] = get(new_cases,current_country,zeros(num_days))
    for day in 1:num_days
        start = day-7
        if start<1
            start=1
        end
        new_cases[current_country][day] = total_cases_to_date[current_country][day] - total_cases_to_date[current_country][start]
    end
end
new_cases

Dict{String,Array} with 7 entries:
  "Germany"        => [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 4.0, 4.0, 4.0, 5.0  …  372…
  "South Korea"    => [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0…
  "United Kingdom" => [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0  …  140…
  "China"          => [0.0, 95.0, 372.0, 858.0, 1527.0, 2329.0, 4961.0, 5539.0,…
  "Japan"          => [0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 5.0, 5.0, 9.0, 13.0  …  76…
  "France"         => [0.0, 0.0, 2.0, 3.0, 3.0, 3.0, 4.0, 5.0, 5.0, 3.0  …  244…
  "US"             => [0.0, 0.0, 1.0, 1.0, 4.0, 4.0, 4.0, 4.0, 4.0, 5.0  …  107…

In [22]:
@manipulate for day in 1:num_days
    plot()
    for current_country in countries
        confirmed = data_dict[current_country][1:day]
        newcases = new_cases[current_country][1:day]
        
        confirmed = replace(confirmed, 0=>NaN)
        newcases = replace(newcases, 0=>NaN)
        
        plot!(confirmed, newcases,  leg=:topleft, label=current_country)
        scatter!(confirmed[end:end], newcases[end:end],label="")
        annotate!(confirmed[day],newcases[day], text(current_country,10, :black))
    end
    xlabel!("Number of Confirmed Cases")
    ylabel!("Number of New Cases (last 7 days)")
    title!("COVID-19 New vs Total Cases")
end

Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Scope(Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :label), Any["day"], Dict{Symbol,Any}(:className => "interact ",:style => Dict{Any,Any}(:padding => "5px 10px 0px 10px")))], Dict{Symbol,Any}(:className => "interact-flex-row-left")), Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :input), Any[], Dict{Symbol,Any}(:max => 77,:min => 1,:attributes => Dict{Any,Any}(:type => "range",Symbol("data-bind") => "numericValue: index, valueUpdate: 'input', event: {change: function (){this.changes(this.changes()+1)}}","orient" => "horizontal"),:step => 1,:className => "slider slider is-fullwidth",:style => Dict{Any,Any}()))], Dict{Symbol,Any}(:className => "interact-flex-row-center")), Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :p), Any[], Dict{Symbol,Any}(:attributes => Dict("data-bind" => "text: formatted_val")))], Dict{Symbol,Any}(:className => "interact-flex-row-right"))], Dict{Symbol,Any}(:className => "interact-flex-row interact-widget")), Dict{String,Tuple{Observables.AbstractObservable,Union{Nothing, Bool}}}("changes" => (Observable{Int64} with 1 listeners. Value:
0, nothing),"index" => (Observable{Int64} with 2 listeners. Value:
39, nothing)), Set(String[]), nothing, Asset[Asset("js", "knockout", "/Users/saumyarawat/.julia/packages/Knockout/IP1uR/src/../assets/knockout.js"), Asset("js", "knockout_punches", "/Users/saumyarawat/.julia/packages/Knockout/IP1uR/src/../assets/knockout_punches.js"), Asset("js", nothing, "/Users/saumyarawat/.julia/packages/InteractBase/9mFwe/src/../assets/all.js"), Asset("css", nothing, "/Users/saumyarawat/.julia/packages/InteractBase/9mFwe/src/../assets/style.css"), Asset("css", nothing, "/Users/saumyarawat/.julia/packages/Interact/SbgIk/src/../assets/bulma_confined.min.css")], Dict{Any,Any}("changes" => Any[WebIO.JSString("(function (val){return (val!=this.model[\"changes\"]()) ? (this.valueFromJulia[\"changes\"]=true, this.model[\"changes\"](val)) : undefined})")],"index" => Any[WebIO.JSString("(function (val){return (val!=this.model[\"index\"]()) ? (this.valueFromJulia[\"index\"]=true, this.model[\"index\"](val)) : undefined})")]), WebIO.ConnectionPool(Channel{Any}(sz_max:32,sz_curr:0), Set(AbstractConnection[]), Base.GenericCondition{Base.AlwaysLockedST}(Base.InvasiveLinkedList{Task}(Task (runnable) @0x0000000110e698d0, Task (runnable) @0x0000000110e698d0), Base.AlwaysLockedST(1))), WebIO.JSString[WebIO.JSString("function () {\n    var handler = (function (ko, koPunches) {\n    ko.punches.enableAll();\n    ko.bindingHandlers.numericValue = {\n        init: function(element, valueAccessor, allBindings, data, context) {\n            var stringified = ko.observable(ko.unwrap(valueAccessor()));\n            stringified.subscribe(function(value) {\n                var val = parseFloat(value);\n                if (!isNaN(val)) {\n                    valueAccessor()(val);\n                }\n            });\n            valueAccessor().subscribe(function(value) {\n                var str = JSON.stringify(value);\n                if ((str == \"0\") && ([\"-0\", \"-0.\"].indexOf(stringified()) >= 0))\n                     return;\n                 if ([\"null\", \"\"].indexOf(str) >= 0)\n                     return;\n                stringified(str);\n            });\n            ko.applyBindingsToNode(\n                element,\n                {\n                    value: stringified,\n                    valueUpdate: allBindings.get('valueUpdate'),\n                },\n                context,\n            );\n        }\n    };\n    var json_data = {\"formatted_vals\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\

Exercise 3: Helping with Transcripts

I proofread and corrected lines 48-59 of lecture 3.